---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: grafeas-image-signing-webhook
  labels:
    app: grafeas-image-signing-webhook
    kind: validator
webhooks:
  - name: deployment.admission.kubesc.io
    clientConfig:
      service:
        name: grafeas-image-signing-webhook
        namespace: grafeas-image-signing
        path: "/deployment"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJBQ0NRREs1M295TWY5NGJUQU5CZ2txaGtpRzl3MEJBUVVGQURBbU1TUXdJZ1lEVlFRRERCdHIKZFdKbGMyVmpMWGRsWW1odmIyc3VhM1ZpWlhObFl5NXpkbU13SGhjTk1UZ3dOekk1TWpJMU1EQTJXaGNOTVRrdwpOekk1TWpJMU1EQTJXakFtTVNRd0lnWURWUVFEREJ0cmRXSmxjMlZqTFhkbFltaHZiMnN1YTNWaVpYTmxZeTV6CmRtTXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEdWZNZ1htSG95MmFUQTh1dTMKcTlpVGNFL0xFMjIrMHBuTlovdE05VVl3Rm85OE01YVJvQm1sa0NjNDFpb1VXaHJKeklvUVQyUUkzblBPMkMwUQpodkNGTnhEMXdKdWtGclZXUU5DZENmbm15dkErdzdRYkRURVhmSm9ZeVNSM2RPeHF1UE9ndGc0Zk53Nk9TSlJyClgvdWFiS0FpQkxNaU5IRmZlUTUwdVREckhhU0FDdGxxWVBQdWE4dU1BMVhqYTNFQlFvNVB4bEVhQk9XQXB4aksKd01rVUxOOTRzU0IvS05CN25rZUhoWW13am9hY25PVUErc1RHYzBrclpNNjFydDhpSXZleDZXbm5sRXE0QythZgpSQ0tLOS8rQ1g3VkJjV3MxdEFPWkNuRklBY1VacHNJU0RjOE9NTmhVcEpXQ3BzcmF3YlBvVWtHR1pOOGFmaDBTCi9BNnRBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUZCUUFEZ2dFQkFKOHR6d05sNW1CeUM3V2FGNXlWUlI2aTJFWWQKL0FFZG04RFNLSWE5Q3dyUXBKR1VPVU1ycXcyaFdaOFNxckNzZkJtWUVEUG1zOE5tRTB6S2hTWS81SVFYZFA4YwphL2kvRFFSKzBXREtFVlFXT2Q5dWg5N21jVmtkMTc3eVN1clFpYjVkTzkycG1nQW1KcEdNaGllMjJ1elhoZ2RQCkw5cGphRUVaa3E1aXdKa3EyNHg0anY2Tk9YVUNHNUkrZ2crVVVJNnA1czFhT29xRC94Tk9XV0U4c1B5cENraUMKRzZ0MnJUU0RNQmtxTUtTd1VsN1NPZVp1TWZjUWVmYng4Q0JyOVE1U3FCOEdwMExIMmM3ZVZ6Y3pLOGE1Sm02aApIOFJER0xNV25VR1BtaTZBM3hWZFhsMW1Ic0htazY0OWdpdW5WY09peE8rKzBJZTFyeDBsTjY1VW9tZz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations:
        - CREATE
        - UPDATE
        apiGroups:
        - apps
        - extensions
        apiVersions:
        - "*"
        resources:
        - deployments
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        grafeas-image-signing-validation: enabled
  - name: daemonset.admission.kubesc.io
    clientConfig:
      service:
        name: grafeas-image-signing-webhook
        namespace: grafeas-image-signing
        path: "/daemonset"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJBQ0NRREs1M295TWY5NGJUQU5CZ2txaGtpRzl3MEJBUVVGQURBbU1TUXdJZ1lEVlFRRERCdHIKZFdKbGMyVmpMWGRsWW1odmIyc3VhM1ZpWlhObFl5NXpkbU13SGhjTk1UZ3dOekk1TWpJMU1EQTJXaGNOTVRrdwpOekk1TWpJMU1EQTJXakFtTVNRd0lnWURWUVFEREJ0cmRXSmxjMlZqTFhkbFltaHZiMnN1YTNWaVpYTmxZeTV6CmRtTXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEdWZNZ1htSG95MmFUQTh1dTMKcTlpVGNFL0xFMjIrMHBuTlovdE05VVl3Rm85OE01YVJvQm1sa0NjNDFpb1VXaHJKeklvUVQyUUkzblBPMkMwUQpodkNGTnhEMXdKdWtGclZXUU5DZENmbm15dkErdzdRYkRURVhmSm9ZeVNSM2RPeHF1UE9ndGc0Zk53Nk9TSlJyClgvdWFiS0FpQkxNaU5IRmZlUTUwdVREckhhU0FDdGxxWVBQdWE4dU1BMVhqYTNFQlFvNVB4bEVhQk9XQXB4aksKd01rVUxOOTRzU0IvS05CN25rZUhoWW13am9hY25PVUErc1RHYzBrclpNNjFydDhpSXZleDZXbm5sRXE0QythZgpSQ0tLOS8rQ1g3VkJjV3MxdEFPWkNuRklBY1VacHNJU0RjOE9NTmhVcEpXQ3BzcmF3YlBvVWtHR1pOOGFmaDBTCi9BNnRBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUZCUUFEZ2dFQkFKOHR6d05sNW1CeUM3V2FGNXlWUlI2aTJFWWQKL0FFZG04RFNLSWE5Q3dyUXBKR1VPVU1ycXcyaFdaOFNxckNzZkJtWUVEUG1zOE5tRTB6S2hTWS81SVFYZFA4YwphL2kvRFFSKzBXREtFVlFXT2Q5dWg5N21jVmtkMTc3eVN1clFpYjVkTzkycG1nQW1KcEdNaGllMjJ1elhoZ2RQCkw5cGphRUVaa3E1aXdKa3EyNHg0anY2Tk9YVUNHNUkrZ2crVVVJNnA1czFhT29xRC94Tk9XV0U4c1B5cENraUMKRzZ0MnJUU0RNQmtxTUtTd1VsN1NPZVp1TWZjUWVmYng4Q0JyOVE1U3FCOEdwMExIMmM3ZVZ6Y3pLOGE1Sm02aApIOFJER0xNV25VR1BtaTZBM3hWZFhsMW1Ic0htazY0OWdpdW5WY09peE8rKzBJZTFyeDBsTjY1VW9tZz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations:
        - CREATE
        - UPDATE
        apiGroups:
        - apps
        - extensions
        apiVersions:
        - "*"
        resources:
        - daemonsets
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        grafeas-image-signing-validation: enabled
  - name: statefulset.admission.kubesc.io
    clientConfig:
      service:
        name: grafeas-image-signing-webhook
        namespace: grafeas-image-signing
        path: "/statefulset"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJBQ0NRREs1M295TWY5NGJUQU5CZ2txaGtpRzl3MEJBUVVGQURBbU1TUXdJZ1lEVlFRRERCdHIKZFdKbGMyVmpMWGRsWW1odmIyc3VhM1ZpWlhObFl5NXpkbU13SGhjTk1UZ3dOekk1TWpJMU1EQTJXaGNOTVRrdwpOekk1TWpJMU1EQTJXakFtTVNRd0lnWURWUVFEREJ0cmRXSmxjMlZqTFhkbFltaHZiMnN1YTNWaVpYTmxZeTV6CmRtTXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEdWZNZ1htSG95MmFUQTh1dTMKcTlpVGNFL0xFMjIrMHBuTlovdE05VVl3Rm85OE01YVJvQm1sa0NjNDFpb1VXaHJKeklvUVQyUUkzblBPMkMwUQpodkNGTnhEMXdKdWtGclZXUU5DZENmbm15dkErdzdRYkRURVhmSm9ZeVNSM2RPeHF1UE9ndGc0Zk53Nk9TSlJyClgvdWFiS0FpQkxNaU5IRmZlUTUwdVREckhhU0FDdGxxWVBQdWE4dU1BMVhqYTNFQlFvNVB4bEVhQk9XQXB4aksKd01rVUxOOTRzU0IvS05CN25rZUhoWW13am9hY25PVUErc1RHYzBrclpNNjFydDhpSXZleDZXbm5sRXE0QythZgpSQ0tLOS8rQ1g3VkJjV3MxdEFPWkNuRklBY1VacHNJU0RjOE9NTmhVcEpXQ3BzcmF3YlBvVWtHR1pOOGFmaDBTCi9BNnRBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUZCUUFEZ2dFQkFKOHR6d05sNW1CeUM3V2FGNXlWUlI2aTJFWWQKL0FFZG04RFNLSWE5Q3dyUXBKR1VPVU1ycXcyaFdaOFNxckNzZkJtWUVEUG1zOE5tRTB6S2hTWS81SVFYZFA4YwphL2kvRFFSKzBXREtFVlFXT2Q5dWg5N21jVmtkMTc3eVN1clFpYjVkTzkycG1nQW1KcEdNaGllMjJ1elhoZ2RQCkw5cGphRUVaa3E1aXdKa3EyNHg0anY2Tk9YVUNHNUkrZ2crVVVJNnA1czFhT29xRC94Tk9XV0U4c1B5cENraUMKRzZ0MnJUU0RNQmtxTUtTd1VsN1NPZVp1TWZjUWVmYng4Q0JyOVE1U3FCOEdwMExIMmM3ZVZ6Y3pLOGE1Sm02aApIOFJER0xNV25VR1BtaTZBM3hWZFhsMW1Ic0htazY0OWdpdW5WY09peE8rKzBJZTFyeDBsTjY1VW9tZz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations:
        - CREATE
        apiGroups:
        - apps
        apiVersions:
        - "*"
        resources:
        - statefulsets
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        grafeas-image-signing-validation: enabled
